const GET_KKPT_CONTROL_START = "GET_KKPT_CONTROL_START"
const GET_KKPT_CONTROL_SUCCESS = "GET_KKPT_CONTROL_SUCCESS"
const GET_KKPT_CONTROL_FAILED = "GET_KKPT_CONTROL_FAILED"

const CREATE_KKPT_CONTROL_START = "CREATE_KKPT_CONTROL_START"
const CREATE_KKPT_CONTROL_SUCCESS = "CREATE_KKPT_CONTROL_SUCCESS"
const CREATE_KKPT_CONTROL_FAILED = "CREATE_KKPT_CONTROL_FAILED"




export {
    GET_KKPT_CONTROL_FAILED,
    GET_KKPT_CONTROL_START,
    GET_KKPT_CONTROL_SUCCESS,
    CREATE_KKPT_CONTROL_START,
    CREATE_KKPT_CONTROL_FAILED,
    CREATE_KKPT_CONTROL_SUCCESS,
}