const prefix = "MAPA_SAMPLE_FILE";

export const FETCH_MAPA_SAMPLE_FILE_START = `${prefix}/FETCH_MAPA_SAMPLE_FILE_START`;
export const FETCH_MAPA_SAMPLE_FILE_SUCCESSFUL = `${prefix}/FETCH_MAPA_SAMPLE_FILE_SUCCESSFUL`;
export const FETCH_MAPA_SAMPLE_FILE_FAILED = `${prefix}/FETCH_MAPA_SAMPLE_FILE_FAILED`;

export const FETCH_POOL_SAMPLE_FILE_START = `${prefix}/FETCH_POOL_SAMPLE_FILE_START`;
export const FETCH_POOL_SAMPLE_FILE_SUCCESSFUL = `${prefix}/FETCH_POOL_SAMPLE_FILE_SUCCESSFUL`;
export const FETCH_POOL_SAMPLE_FILE_FAILED = `${prefix}/FETCH_POOL_SAMPLE_FILE_FAILED`;

export const SUBMIT_UPLOAD_SAMPLE_FILE_START = `${prefix}/SUBMIT_UPLOAD_SAMPLE_FILE_START`;
export const SUBMIT_UPLOAD_SAMPLE_FILE_SUCCESSFUL = `${prefix}/SUBMIT_UPLOAD_SAMPLE_FILE_SUCCESSFUL`;
export const SUBMIT_UPLOAD_SAMPLE_FILE_FAILED = `${prefix}/SUBMIT_UPLOAD_SAMPLE_FILE_FAILED`;

export const SUBMIT_UPDATE_MAPA_SAMPLE_FILE_START = `${prefix}/SUBMIT_UPDATE_MAPA_SAMPLE_FILE_START`;
export const SUBMIT_UPDATE_MAPA_SAMPLE_FILE_SUCCESSFUL = `${prefix}/SUBMIT_UPDATE_MAPA_SAMPLE_FILE_SUCCESSFUL`;
export const SUBMIT_UPDATE_MAPA_SAMPLE_FILE_FAILED = `${prefix}/SUBMIT_UPDATE_MAPA_SAMPLE_FILE_FAILED`;

export const SUBMIT_SAVE_MAPA_SAMPLE_FILE_START = `${prefix}/SUBMIT_SAVE_MAPA_SAMPLE_FILE_START`;
export const SUBMIT_SAVE_MAPA_SAMPLE_FILE_SUCCESSFUL = `${prefix}/SUBMIT_SAVE_MAPA_SAMPLE_FILE_SUCCESSFUL`;
export const SUBMIT_SAVE_MAPA_SAMPLE_FILE_FAILED = `${prefix}/SUBMIT_SAVE_MAPA_SAMPLE_FILE_FAILED`;

export const DELETE_MAPA_SAMPLE_FILE_START = `${prefix}/DELETE_MAPA_SAMPLE_FILE_START`;
export const DELETE_MAPA_SAMPLE_FILE_SUCCESSFUL = `${prefix}/DELETE_MAPA_SAMPLE_FILE_SUCCESSFUL`;
export const DELETE_MAPA_SAMPLE_FILE_FAILED = `${prefix}/DELETE_MAPA_SAMPLE_FILE_FAILED`;

export const DELETE_POOL_SAMPLE_FILE_START = `${prefix}/DELETE_POOL_SAMPLE_FILE_START`;
export const DELETE_POOL_SAMPLE_FILE_SUCCESSFUL = `${prefix}/DELETE_POOL_SAMPLE_FILE_SUCCESSFUL`;
export const DELETE_POOL_SAMPLE_FILE_FAILED = `${prefix}/DELETE_POOL_SAMPLE_FILE_FAILED`;
