const GET_KKPA_SAMPLE_START = "GET_KKPA_SAMPLE_START"
const GET_KKPA_SAMPLE_SUCCESS = "GET_KKPA_SAMPLE_SUCCESS"
const GET_KKPA_SAMPLE_FAILED = "GET_KKPA_SAMPLE_FAILED"

const SELECT_KKPA_SAMPLE_START = "SELECT_KKPA_SAMPLE_START"
const SELECT_KKPA_SAMPLE_SUCCESS = "SELECT_KKPA_SAMPLE_SUCCESS"
const SELECT_KKPA_SAMPLE_FAILED = "SELECT_KKPA_SAMPLE_FAILED"
const SELECT_KKPA_SAMPLE_EMPTY_SAMPLE = "SELECT_KKPA_SAMPLE_EMPTY_SAMPLE"


export {
    GET_KKPA_SAMPLE_FAILED,
    GET_KKPA_SAMPLE_START,
    GET_KKPA_SAMPLE_SUCCESS,
    SELECT_KKPA_SAMPLE_START,
    SELECT_KKPA_SAMPLE_SUCCESS,
    SELECT_KKPA_SAMPLE_FAILED,
    SELECT_KKPA_SAMPLE_EMPTY_SAMPLE
}