const SAVE_PRO_AUDIT_LOADING = "SAVE_PRO_AUDIT_LOADING"
const SAVE_PRO_AUDIT_FAILED = "SAVE_PRO_AUDIT_FAILED"
const SAVE_PRO_AUDIT_SUCCESS = "SAVE_PRO_AUDIT_SUCCESS"

export {
    SAVE_PRO_AUDIT_LOADING,
    SAVE_PRO_AUDIT_FAILED,
    SAVE_PRO_AUDIT_SUCCESS
}