const FETCH_CONTENT_START = "FETCH_CONTENT_START"
const FECTH_CONTENT_SUCCESS = "FECTH_CONTENT_SUCCESS"
const FETCH_CONTENT_FAILED = "FETCH_CONTENT_FAILED"

export {
    FETCH_CONTENT_START,
    FECTH_CONTENT_SUCCESS,
    FETCH_CONTENT_FAILED
}