const GET_REFERENCE_KKPT_PENYEBAB_START = "GET_REFERENCE_KKPT_START"
const GET_REFERENCE_KKPT_PENYEBAB_SUCCESS = "GET_REFERENCE_KKPT_SUCCESS"
const GET_REFERENCE_KKPT_PENYEBAB_FAILED = "GET_REFERENCE_KKPT_FAILED"

export {
    GET_REFERENCE_KKPT_PENYEBAB_START,
    GET_REFERENCE_KKPT_PENYEBAB_SUCCESS,
    GET_REFERENCE_KKPT_PENYEBAB_FAILED
}