const FETCH_START_LIST = "FETCH_START_LIST"
const FECTH_SUCCESS_LIST = "FECTH_SUCCESS_LIST"
const FETCH_FAILED_LIST = "FETCH_FAILED_LIST"

const CREATE_MERGE_START = "CREATE_MERGE_START"
const CREATE_MERGE_SUCCESS = "CREATE_MERGE_SUCCESS"
const CREATE_MERGE_FAILED = "CREATE_MERGE_FAILED"

const GET_MERGE_HISTORY_START = "GET_MERGE_HISTORY_START"
const GET_MERGE_HISTORY_SUCCESS = "GET_MERGE_HISTORY_SUCCESS"
const GET_MERGE_HISTORY_FAILED = "GET_MERGE_HISTORY_FAILED"

export {
    FETCH_START_LIST,
    FECTH_SUCCESS_LIST,
    FETCH_FAILED_LIST,
    CREATE_MERGE_START,
    CREATE_MERGE_SUCCESS,
    CREATE_MERGE_FAILED,
    GET_MERGE_HISTORY_START,
    GET_MERGE_HISTORY_SUCCESS,
    GET_MERGE_HISTORY_FAILED
}