const prefix = "PAT_DOCUMENT_HISTORY";

export const FETCH_DOCUMENTS_START = `${prefix}/FETCH_DOCUMENTS_START`;
export const FETCH_DOCUMENTS_SUCCESSFUL = `${prefix}/FETCH_DOCUMENTS_SUCCESSFUL`;
export const FETCH_DOCUMENTS_FAILED = `${prefix}/FETCH_DOCUMENTS_FAILED`;
