const SAVE_KRITERIA_LOADING = "SAVE_KRITERIA_LOADING"
const SAVE_KRITERIA_FAILED = "SAVE_KRITERIA_FAILED"
const SAVE_KRITERIA_SUCCESS = "SAVE_KRITERIA_SUCCESS"

export {
    SAVE_KRITERIA_LOADING,
    SAVE_KRITERIA_FAILED,
    SAVE_KRITERIA_SUCCESS
}