const prefix = "REFERENCE";

export const FETCH_TIPE_AUDIT_START = `${prefix}/FETCH_TIPE_AUDIT_START`;
export const FETCH_TIPE_AUDIT_SUCCESSFUL = `${prefix}/FETCH_TIPE_AUDIT_SUCCESSFUL`;
export const FETCH_TIPE_AUDIT_FAILED = `${prefix}/FETCH_TIPE_AUDIT_FAILED`;

export const FETCH_TEMA_AUDIT_START = `${prefix}/FETCH_TEMA_AUDIT_START`;
export const FETCH_TEMA_AUDIT_SUCCESSFUL = `${prefix}/FETCH_TEMA_AUDIT_SUCCESSFUL`;
export const FETCH_TEMA_AUDIT_FAILED = `${prefix}/FETCH_TEMA_AUDIT_FAILED`;

export const FETCH_TIPE_OBJEK_START = `${prefix}/FETCH_TIPE_OBJEK_START`;
export const FETCH_TIPE_OBJEK_SUCCESSFUL = `${prefix}/FETCH_TIPE_OBJEK_SUCCESSFUL`;
export const FETCH_TIPE_OBJEK_FAILED = `${prefix}/FETCH_TIPE_OBJEK_FAILED`;

export const FETCH_ECHANNEL_START = `${prefix}/FETCH_ECHANNEL_START`;
export const FETCH_ECHANNEL_SUCCESSFUL = `${prefix}/FETCH_ECHANNEL_SUCCESSFUL`;
export const FETCH_ECHANNEL_FAILED = `${prefix}/FETCH_ECHANNEL_FAILED`;

export const FETCH_KATEGORI_ANGGARAN_START = `${prefix}/FETCH_KATEGORI_ANGGARAN_START`;
export const FETCH_KATEGORI_ANGGARAN_SUCCESSFUL = `${prefix}/FETCH_KATEGORI_ANGGARAN_SUCCESSFUL`;
export const FETCH_KATEGORI_ANGGARAN_FAILED = `${prefix}/FETCH_KATEGORI_ANGGARAN_FAILED`;

export const FETCH_TEAMS_START = `${prefix}/FETCH_TEAMS_START`;
export const FETCH_TEAMS_SUCCESSFUL = `${prefix}/FETCH_TEAMS_SUCCESSFUL`;
export const FETCH_TEAMS_FAILED = `${prefix}/FETCH_TEAMS_FAILED`;

export const FETCH_TEAMS_ADDENDUM_START = `${prefix}/FETCH_TEAMS_ADDENDUM_START`;
export const FETCH_TEAMS_ADDENDUM_SUCCESSFUL = `${prefix}/FETCH_TEAMS_ADDENDUM_SUCCESSFUL`;
export const FETCH_TEAMS_ADDENDUM_FAILED = `${prefix}/FETCH_TEAMS_ADDENDUM_FAILED`;

export const FETCH_UKO_START = `${prefix}/FETCH_UKO_START`;
export const FETCH_UKO_SUCCESSFUL = `${prefix}/FETCH_UKO_SUCCESSFUL`;
export const FETCH_UKO_FAILED = `${prefix}/FETCH_UKO_FAILED`;
