const GET_KKPT_LIKEHOOD_START = "GET_KKPT_LIKEHOOD_START"
const GET_KKPT_LIKEHOOD_SUCCESS = "GET_KKPT_LIKEHOOD_SUCCESS"
const GET_KKPT_LIKEHOOD_FAILED = "GET_KKPT_LIKEHOOD_FAILED"


export {
    GET_KKPT_LIKEHOOD_FAILED,
    GET_KKPT_LIKEHOOD_START,
    GET_KKPT_LIKEHOOD_SUCCESS
}