const SAVE_APPROVAL_KKPT_START = "SAVE_APPROVAL_KKPT_START"
const SAVE_APPROVAL_KKPT_SUCCESS = "SAVE_APPROVAL_KKPT_SUCCESS"
const SAVE_APPROVAL_KKPT_FAILED = "SAVE_APPROVAL_KKPT_FAILED"

const SAVE_NA_KKPT_START = "SAVE_NA_KKPT_START"
const SAVE_NA_KKPT_SUCCESS = "SAVE_NA_KKPT_SUCCESS"
const SAVE_NA_KKPT_FAILED = "SAVE_NA_KKPT_FAILED"



export {
    SAVE_APPROVAL_KKPT_FAILED,
    SAVE_APPROVAL_KKPT_START,
    SAVE_APPROVAL_KKPT_SUCCESS,
    SAVE_NA_KKPT_START,
    SAVE_NA_KKPT_SUCCESS,
    SAVE_NA_KKPT_FAILED
}