const SAVE_KELEMAHAN_KKPT_START = "SAVE_KELEMAHAN_KKPT_START"
const SAVE_KELEMAHAN_KKPT_SUCCESS = "SAVE_KELEMAHAN_KKPT_SUCCESS"
const SAVE_KELEMAHAN_KKPT_FAILED = "SAVE_KELEMAHAN_KKPT_FAILED"

export {
    SAVE_KELEMAHAN_KKPT_FAILED,
    SAVE_KELEMAHAN_KKPT_START,
    SAVE_KELEMAHAN_KKPT_SUCCESS
}