const prefix = "MAPA_ANALISIS_PERENCANAAN";

export const FETCH_START = `${prefix}/FETCH_START`;
export const FETCH_SUCCESSFUL = `${prefix}/FETCH_SUCCESSFUL`;
export const FETCH_FAILED = `${prefix}/FETCH_FAILED`;

export const SUBMIT_START = `${prefix}/SUBMIT_START`;
export const SUBMIT_SUCCESSFUL = `${prefix}/SUBMIT_SUCCESSFUL`;
export const SUBMIT_FAILED = `${prefix}/SUBMIT_FAILED`;

export const FETCH_ANALYZING_START = `${prefix}/FETCH_ANALYZING_START`;
export const FETCH_ANALYZING_SUCCESSFUL = `${prefix}/FETCH_ANALYZING_SUCCESSFUL`;
export const FETCH_ANALYZING_FAILED = `${prefix}/FETCH_ANALYZING_FAILED`;

export const FETCH_AKTIVITAS_START = `${prefix}/FETCH_AKTIVITAS_START`;
export const FETCH_AKTIVITAS_SUCCESSFUL = `${prefix}/FETCH_AKTIVITAS_SUCCESSFUL`;
export const FETCH_AKTIVITAS_FAILED = `${prefix}/FETCH_AKTIVITAS_FAILED`;

export const FETCH_SUB_AKTIVITAS_START = `${prefix}/FETCH_SUB_AKTIVITAS_START`;
export const FETCH_SUB_AKTIVITAS_SUCCESSFUL = `${prefix}/FETCH_SUB_AKTIVITAS_SUCCESSFUL`;
export const FETCH_SUB_AKTIVITAS_FAILED = `${prefix}/FETCH_SUB_AKTIVITAS_FAILED`;

export const DELETE_SUB_AKTIVITAS_START = `${prefix}/DELETE_SUB_AKTIVITAS_START`;
export const DELETE_SUB_AKTIVITAS_SUCCESSFUL = `${prefix}/DELETE_SUB_AKTIVITAS_SUCCESSFUL`;
export const DELETE_SUB_AKTIVITAS_FAILED = `${prefix}/DELETE_SUB_AKTIVITAS_FAILED`;

export const SUBMIT_ANALISA_AKTIVITAS_START = `${prefix}/SUBMIT_ANALISA_AKTIVITAS_START`;
export const SUBMIT_ANALISA_AKTIVITAS_SUCCESSFUL = `${prefix}/SUBMIT_ANALISA_AKTIVITAS_SUCCESSFUL`;
export const SUBMIT_ANALISA_AKTIVITAS_FAILED = `${prefix}/SUBMIT_ANALISA_AKTIVITAS_FAILED`;

export const FETCH_ANALISA_RISK_START = `${prefix}/FETCH_ANALISA_RISK_START`;
export const FETCH_ANALISA_RISK_SUCCESSFUL = `${prefix}/FETCH_ANALISA_RISK_SUCCESSFUL`;
export const FETCH_ANALISA_RISK_FAILED = `${prefix}/FETCH_ANALISA_RISK_FAILED`;

export const FETCH_BREADCRUMB_AKTIVITAS_START = `${prefix}/FETCH_BREADCRUMB_AKTIVITAS_START`;
export const FETCH_BREADCRUMB_AKTIVITAS_SUCCESSFUL = `${prefix}/FETCH_BREADCRUMB_AKTIVITAS_SUCCESSFUL`;
export const FETCH_BREADCRUMB_AKTIVITAS_FAILED = `${prefix}/FETCH_BREADCRUMB_AKTIVITAS_FAILED`;

export const SUBMIT_ANALISA_RISK_START = `${prefix}/SUBMIT_ANALISA_RISK_START`;
export const SUBMIT_ANALISA_RISK_SUCCESSFUL = `${prefix}/SUBMIT_ANALISA_RISK_SUCCESSFUL`;
export const SUBMIT_ANALISA_RISK_FAILED = `${prefix}/SUBMIT_ANALISA_RISK_FAILED`;

export const SUBMIT_PROGRAM_AUDIT_START = `${prefix}/SUBMIT_PROGRAM_AUDIT_START`;
export const SUBMIT_PROGRAM_AUDIT_SUCCESSFUL = `${prefix}/SUBMIT_PROGRAM_AUDIT_SUCCESSFUL`;
export const SUBMIT_PROGRAM_AUDIT_FAILED = `${prefix}/SUBMIT_PROGRAM_AUDIT_FAILED`;

export const SUBMIT_KRITERIA_AUDIT_START = `${prefix}/SUBMIT_KRITERIA_AUDIT_START`;
export const SUBMIT_KRITERIA_AUDIT_SUCCESSFUL = `${prefix}/SUBMIT_KRITERIA_AUDIT_SUCCESSFUL`;
export const SUBMIT_KRITERIA_AUDIT_FAILED = `${prefix}/SUBMIT_KRITERIA_AUDIT_FAILED`;

export const FETCH_SUMMARY_START = `${prefix}/FETCH_SUMMARY_START`;
export const FETCH_SUMMARY_SUCCESSFUL = `${prefix}/FETCH_SUMMARY_SUCCESSFUL`;
export const FETCH_SUMMARY_FAILED = `${prefix}/FETCH_SUMMARY_FAILED`;

export const FETCH_TEKNIK_SAMPLE_START = `${prefix}/FETCH_TEKNIK_SAMPLE_START`;
export const FETCH_TEKNIK_SAMPLE_SUCCESSFUL = `${prefix}/FETCH_TEKNIK_SAMPLE_SUCCESSFUL`;
export const FETCH_TEKNIK_SAMPLE_FAILED = `${prefix}/FETCH_TEKNIK_SAMPLE_FAILED`;

export const SUBMIT_MAPA_SAMPLE_START = `${prefix}/SUBMIT_MAPA_SAMPLE_START`;
export const SUBMIT_MAPA_SAMPLE_SUCCESSFUL = `${prefix}/SUBMIT_MAPA_SAMPLE_SUCCESSFUL`;
export const SUBMIT_MAPA_SAMPLE_FAILED = `${prefix}/SUBMIT_MAPA_SAMPLE_FAILED`;

export const FETCH_MAPA_SAMPLE_START = `${prefix}/FETCH_MAPA_SAMPLE_START`;
export const FETCH_MAPA_SAMPLE_SUCCESSFUL = `${prefix}/FETCH_MAPA_SAMPLE_SUCCESSFUL`;
export const FETCH_MAPA_SAMPLE_FAILED = `${prefix}/FETCH_MAPA_SAMPLE_FAILED`;

export const SUBMIT_APPROVAL_START = `${prefix}/SUBMIT_APPROVAL_START`;
export const SUBMIT_APPROVAL_SUCCESSFUL = `${prefix}/SUBMIT_APPROVAL_SUCCESSFUL`;
export const SUBMIT_APPROVAL_FAILED = `${prefix}/SUBMIT_APPROVAL_FAILED`;

export const FETCH_COMMENT_APPROVAL_START = `${prefix}/FETCH_COMMENT_APPROVAL_START`;
export const FETCH_COMMENT_APPROVAL_SUCCESSFUL = `${prefix}/FETCH_COMMENT_APPROVAL_SUCCESSFUL`;
export const FETCH_COMMENT_APPROVAL_FAILED = `${prefix}/FETCH_COMMENT_APPROVAL_FAILED`;

export const SET_NOTE_REJECT = `${prefix}/SET_NOTE_REJECT`;
