const FETCH_DETAIL_KKPT_START = "FETCH_DETAIL_KKPT_START"
const FECTH_DETAIL_KKPT_SUCCESS = "FECTH_DETAIL_KKPT_SUCCESS"
const FETCH_DETAIL_KKPT_FAILED = "FETCH_DETAIL_KKPT_FAILED"

export {
    FETCH_DETAIL_KKPT_FAILED,
    FETCH_DETAIL_KKPT_START,
    FECTH_DETAIL_KKPT_SUCCESS
}