const GET_KKPT_PENYEBAB_START = "GET_KKPT_PENYEBAB_START"
const GET_KKPT_PENYEBAB_SUCCESS = "GET_KKPT_PENYEBAB_SUCCESS"
const GET_KKPT_PENYEBAB_FAILED = "GET_KKPT_PENYEBAB_FAILED"

const CREATE_KKPT_PENYEBAB_START = "CREATE_KKPT_START"
const CREATE_KKPT_PENYEBAB_SUCCESS = "CREATE_KKPT_SUCCESS"
const CREATE_KKPT_PENYEBAB_FAILED = "CREATE_KKPT_FAILED"



const DELETE_KKPT_PENYEBAB_START = "DELETE_KKPT_START"
const DELETE_KKPT_PENYEBAB_SUCCESS = "DELETE_KKPT_SUCCESS"
const DELETE_KKPT_PENYEBAB_FAILED = "DELETE_KKPT_FAILED"


export {
    GET_KKPT_PENYEBAB_FAILED,
    GET_KKPT_PENYEBAB_START,
    GET_KKPT_PENYEBAB_SUCCESS,
    CREATE_KKPT_PENYEBAB_START,
    CREATE_KKPT_PENYEBAB_FAILED,
    CREATE_KKPT_PENYEBAB_SUCCESS,
    DELETE_KKPT_PENYEBAB_START,
    DELETE_KKPT_PENYEBAB_SUCCESS,
    DELETE_KKPT_PENYEBAB_FAILED,

}