const GET_KKPT_START = "GET_KKPT_START";
const GET_KKPT_SUCCESS = "GET_KKPT_SUCCESS";
const GET_KKPT_FAILED = "GET_KKPT_FAILED";

const CREATE_KKPT_START = "CREATE_KKPT_START";
const CREATE_KKPT_SUCCESS = "CREATE_KKPT_SUCCESS";
const CREATE_KKPT_FAILED = "CREATE_KKPT_FAILED";



export {
    GET_KKPT_START,
    GET_KKPT_SUCCESS,
    GET_KKPT_FAILED,
    CREATE_KKPT_START,
    CREATE_KKPT_SUCCESS,
    CREATE_KKPT_FAILED
} 