const SAVE_KONDISI_KKPT_START = "SAVE_KONDISI_KKPT_START"
const SAVE_KONDISI_KKPT_SUCCESS = "SAVE_KONDISI_KKPT_SUCCESS"
const SAVE_KONDISI_KKPT_FAILED = "SAVE_KONDISI_KKPT_FAILED"

export {
    SAVE_KONDISI_KKPT_FAILED,
    SAVE_KONDISI_KKPT_START,
    SAVE_KONDISI_KKPT_SUCCESS
}