const FETCH_START_BAB_KKPT = "FETCH_START_BAB_KKPT"
const FECTH_SUCCESS_BAB_KKPT = "FECTH_SUCCESS_BAB_KKPT"
const FETCH_FAILED_BAB_KKPT = "FETCH_FAILED_BAB_KKPT"

export {
    FETCH_START_BAB_KKPT,
    FECTH_SUCCESS_BAB_KKPT,
    FETCH_FAILED_BAB_KKPT
}