const SAVE_INFO_KKPT_START = "SAVE_INFO_KKPT_START"
const SAVE_INFO_KKPT_SUCCESS = "SAVE_INFO_KKPT_SUCCESS"
const SAVE_INFO_KKPT_FAILED = "SAVE_INFO_KKPT_FAILED"


const GET_TIPE_RESIKO_START = "GET_TIPE_RESIKO_START"
const GET_TIPE_RESIKO_SUCCESS = "GET_TIPE_RESIKO_SUCCESS"
const GET_TIPE_RESIKO_FAILED = "GET_TIPE_RESIKO_FAILED"

const GET_FOCUS_AUDIT_START = "GET_FOCUS_AUDIT_START"
const GET_FOCUS_AUDIT_SUCCESS = "GET_FOCUS_AUDIT_SUCCESS"
const GET_FOCUS_AUDIT_FAILED = "GET_FOCUS_AUDIT_FAILED"

const GET_PRODUK_START = "GET_PRODUK_START"
const GET_PRODUK_SUCCESS = "GET_PRODUK_SUCCESS"
const GET_PRODUK_FAILED = "GET_PRODUK_FAILED"

export {
    SAVE_INFO_KKPT_FAILED,
    SAVE_INFO_KKPT_START,
    SAVE_INFO_KKPT_SUCCESS,
    GET_TIPE_RESIKO_START,
    GET_TIPE_RESIKO_SUCCESS,
    GET_TIPE_RESIKO_FAILED,
    GET_FOCUS_AUDIT_START,
    GET_FOCUS_AUDIT_SUCCESS,
    GET_FOCUS_AUDIT_FAILED,
    GET_PRODUK_START,
    GET_PRODUK_SUCCESS,
    GET_PRODUK_FAILED
}