const SAVE_PENGUJIAN_KKPA_START = "SAVE_PENGUJIAN_KKPA_START"
const SAVE_PENGUJIAN_KKPA_SUCCESS = "SAVE_PENGUJIAN_KKPA_SUCCESS"
const SAVE_PENGUJIAN_KKPA_FAILED = "SAVE_PENGUJIAN_KKPA_FAILED"

export {
    SAVE_PENGUJIAN_KKPA_FAILED,
    SAVE_PENGUJIAN_KKPA_START,
    SAVE_PENGUJIAN_KKPA_SUCCESS
}