const GET_KKPT_DATA_START = "GET_KKPT_DATA_START"
const GET_KKPT_DATA_SUCCESS = "GET_KKPT_DATA_SUCCESS"
const GET_KKPT_DATA_FAILED = "GET_KKPT_DATA_FAILED"

const CONTENT_DATA_DOCUMENT = "CONTENT_DATA_DOCUMENT"


export {
    GET_KKPT_DATA_START,
    GET_KKPT_DATA_SUCCESS,
    GET_KKPT_DATA_FAILED,
    CONTENT_DATA_DOCUMENT,
}