const FETCH_REF_CONTROL_START = "FETCH_REF_CONTROL_START"
const FECTH_REF_CONTROL_SUCCESS = "FECTH_REF_CONTROL_SUCCESS"
const FETCH_REF_CONTROL_FAILED = "FETCH_REF_CONTROL_FAILED"

export {
    FETCH_REF_CONTROL_START,
    FECTH_REF_CONTROL_SUCCESS,
    FETCH_REF_CONTROL_FAILED
}