const GET_REFERENCE_KKPT_DAMPAK_START = "GET_REFERENCE_KKPT_DAMPAK_START"
const GET_REFERENCE_KKPT_DAMPAK_SUCCESS = "GET_REFERENCE_KKPT_DAMPAK_SUCCESS"
const GET_REFERENCE_KKPT_DAMPAK_FAILED = "GET_REFERENCE_KKPT_DAMPAK_FAILED"

export {
    GET_REFERENCE_KKPT_DAMPAK_START,
    GET_REFERENCE_KKPT_DAMPAK_SUCCESS,
    GET_REFERENCE_KKPT_DAMPAK_FAILED
}