const GET_KKPT_DAMPAK_START = "GET_KKPT_DAMPAK_START"
const GET_KKPT_DAMPAK_SUCCESS = "GET_KKPT_DAMPAK_SUCCESS"
const GET_KKPT_DAMPAK_FAILED = "GET_KKPT_DAMPAK_FAILED"

const CREATE_KKPT_DAMPAK_START = "CREATE_KKPT_DAMPAK_START"
const CREATE_KKPT_DAMPAK_SUCCESS = "CREATE_KKPT_DAMPAK_SUCCESS"
const CREATE_KKPT_DAMPAK_FAILED = "CREATE_KKPT_DAMPAK_FAILED"





export {
    GET_KKPT_DAMPAK_FAILED,
    GET_KKPT_DAMPAK_START,
    GET_KKPT_DAMPAK_SUCCESS,
    CREATE_KKPT_DAMPAK_START,
    CREATE_KKPT_DAMPAK_FAILED,
    CREATE_KKPT_DAMPAK_SUCCESS,

}