const prefix = "MAPA_PENUGASAN";

export const FETCH_START = `${prefix}/FETCH_START`;
export const FETCH_SUCCESSFUL = `${prefix}/FETCH_SUCCESSFUL`;
export const FETCH_FAILED = `${prefix}/FETCH_FAILED`;

export const FETCH_SUMMARY_START = `${prefix}/FETCH_SUMMARY_START`;
export const FETCH_SUMMARY_SUCCESSFUL = `${prefix}/FETCH_SUMMARY_SUCCESSFUL`;
export const FETCH_SUMMARY_FAILED = `${prefix}/FETCH_SUMMARY_FAILED`;

export const FETCH_MAPA_SAMPLE_START = `${prefix}/FETCH_MAPA_SAMPLE_START`;
export const FETCH_MAPA_SAMPLE_SUCCESSFUL = `${prefix}/FETCH_MAPA_SAMPLE_SUCCESSFUL`;
export const FETCH_MAPA_SAMPLE_FAILED = `${prefix}/FETCH_MAPA_SAMPLE_FAILED`;

export const SUBMIT_AUDITOR_START = `${prefix}/SUBMIT_AUDITOR_START`;
export const SUBMIT_AUDITOR_SUCCESSFUL = `${prefix}/SUBMIT_AUDITOR_SUCCESSFUL`;
export const SUBMIT_AUDITOR_FAILED = `${prefix}/SUBMIT_AUDITOR_FAILED`;
