const prefix = "RPM_NEGOSIASI";

export const FETCH_STATUS_START = `${prefix}/FETCH_STATUS_START`;
export const FETCH_STATUS_SUCCESSFUL = `${prefix}/FETCH_STATUS_SUCCESSFUL`;
export const FETCH_STATUS_FAILED = `${prefix}/FETCH_STATUS_FAILED`;

export const FETCH_ATTENDANCE_START = `${prefix}/FETCH_ATTENDANCE_START`;
export const FETCH_ATTENDANCE_SUCCESSFUL = `${prefix}/FETCH_ATTENDANCE_SUCCESSFUL`;
export const FETCH_ATTENDANCE_FAILED = `${prefix}/FETCH_ATTENDANCE_FAILED`;
export const UPDATE_ATTENDANCE = `${prefix}/UPDATE_ATTENDANCE`;

export const FETCH_TIM_AUDIT_START = `${prefix}/FETCH_TIM_AUDIT_START`;
export const FETCH_TIM_AUDIT_SUCCESSFUL = `${prefix}/FETCH_TIM_AUDIT_SUCCESSFUL`;
export const FETCH_TIM_AUDIT_FAILED = `${prefix}/FETCH_TIM_AUDIT_FAILED`;

export const FETCH_NOTULEN_START = `${prefix}/FETCH_NOTULEN_START`;
export const FETCH_NOTULEN_SUCCESSFUL = `${prefix}/FETCH_NOTULEN_SUCCESSFUL`;
export const FETCH_NOTULEN_FAILED = `${prefix}/FETCH_NOTULEN_FAILED`;

export const FETCH_BERITA_ACARA_START = `${prefix}/FETCH_BERITA_ACARA_START`;
export const FETCH_BERITA_ACARA_SUCCESSFUL = `${prefix}/FETCH_BERITA_ACARA_SUCCESSFUL`;
export const FETCH_BERITA_ACARA_FAILED = `${prefix}/FETCH_BERITA_ACARA_FAILED`;

export const FETCH_KKPT_NEGO_START = `${prefix}/FETCH_KKPT_NEGO_START`;
export const FETCH_KKPT_NEGO_SUCCESSFUL = `${prefix}/FETCH_KKPT_NEGO_SUCCESSFUL`;
export const FETCH_KKPT_NEGO_FAILED = `${prefix}/FETCH_KKPT_NEGO_FAILED`;

export const FETCH_ACTION_PLAN_START = `${prefix}/FETCH_ACTION_PLAN_START`;
export const FETCH_ACTION_PLAN_SUCCESSFUL = `${prefix}/FETCH_ACTION_PLAN_SUCCESSFUL`;
export const FETCH_ACTION_PLAN_FAILED = `${prefix}/FETCH_ACTION_PLAN_FAILED`;
