const FETCH_DAFTAR_ISI_START = "FETCH_DAFTAR_ISI_START"
const FECTH_DAFTAR_ISI_SUCCESS = "FECTH_DAFTAR_ISI_SUCCESS"
const FETCH_DAFTAR_ISI_FAILED = "FETCH_DAFTAR_ISI_FAILED"

export {
    FETCH_DAFTAR_ISI_START,
    FECTH_DAFTAR_ISI_SUCCESS,
    FETCH_DAFTAR_ISI_FAILED
}