const SAVE_KRITERIA_KKPT_START = "SAVE_KRITERIA_KKPT_START"
const SAVE_KRITERIA_KKPT_SUCCESS = "SAVE_KRITERIA_KKPT_SUCCESS"
const SAVE_KRITERIA_KKPT_FAILED = "SAVE_KRITERIA_KKPT_FAILED"

export {
    SAVE_KRITERIA_KKPT_FAILED,
    SAVE_KRITERIA_KKPT_START,
    SAVE_KRITERIA_KKPT_SUCCESS
}