const GET_KKPT_SAMPLE_START = "GET_KKPT_SAMPLE_START"
const GET_KKPT_SAMPLE_SUCCESS = "GET_KKPT_SAMPLE_SUCCESS"
const GET_KKPT_SAMPLE_FAILED = "GET_KKPT_SAMPLE_FAILED"

const SELECT_KKPT_SAMPLE_START = "SELECT_KKPT_SAMPLE_START"
const SELECT_KKPT_SAMPLE_SUCCESS = "SELECT_KKPT_SAMPLE_SUCCESS"
const SELECT_KKPT_SAMPLE_FAILED = "SELECT_KKPT_SAMPLE_FAILED"
const SELECT_KKPT_SAMPLE_EMPTY_SAMPLE = "SELECT_KKPT_SAMPLE_EMPTY_SAMPLE"


export {
    GET_KKPT_SAMPLE_FAILED,
    GET_KKPT_SAMPLE_START,
    GET_KKPT_SAMPLE_SUCCESS,
    SELECT_KKPT_SAMPLE_START,
    SELECT_KKPT_SAMPLE_SUCCESS,
    SELECT_KKPT_SAMPLE_FAILED,
    SELECT_KKPT_SAMPLE_EMPTY_SAMPLE
}