const FETCH_KKPA_BY_ID_START = "FETCH_KKPA_BY_IDSTART"
const FECTH_KKPA_BY_ID_SUCCESS = "FECTH_KKPA_BY_ID_SUCCESS"
const FETCH_KKPA_BY_ID_FAILED = "FETCH_KKPA_BY_ID_FAILED"

export {
    FETCH_KKPA_BY_ID_START,
    FECTH_KKPA_BY_ID_SUCCESS,
    FETCH_KKPA_BY_ID_FAILED
}