const GET_KKPT_REKOMENDASI_START = "GET_KKPT_REKOMENDASI_START"
const GET_KKPT_REKOMENDASI_SUCCESS = "GET_KKPT_REKOMENDASI_SUCCESS"
const GET_KKPT_REKOMENDASI_FAILED = "GET_KKPT_REKOMENDASI_FAILED"

const CREATE_KKPT_REKOMENDASI_START = "CREATE_KKPT_REKOMENDASI_START"
const CREATE_KKPT_REKOMENDASI_SUCCESS = "CREATE_KKPT_REKOMENDASI_SUCCESS"
const CREATE_KKPT_REKOMENDASI_FAILED = "CREATE_KKPT_REKOMENDASI_FAILED"

const DELETE_KKPT_REKOMENDASI_START = "DELETE_KKPT_REKOMENDASI_START"
const DELETE_KKPT_REKOMENDASI_SUCCESS = "DELETE_KKPT_REKOMENDASI_SUCCESS"
const DELETE_KKPT_REKOMENDASI_FAILED = "DELETE_KKPT_REKOMENDASI_FAILED"






export {
    GET_KKPT_REKOMENDASI_FAILED,
    GET_KKPT_REKOMENDASI_START,
    GET_KKPT_REKOMENDASI_SUCCESS,
    CREATE_KKPT_REKOMENDASI_START,
    CREATE_KKPT_REKOMENDASI_FAILED,
    CREATE_KKPT_REKOMENDASI_SUCCESS,
    DELETE_KKPT_REKOMENDASI_START,
    DELETE_KKPT_REKOMENDASI_SUCCESS,
    DELETE_KKPT_REKOMENDASI_FAILED

}