const prefix = "RPM_AUDITEE";

export const FETCH_PROJECTS_START = `${prefix}/FETCH_PROJECTS_START`;
export const FETCH_PROJECTS_SUCCESSFUL = `${prefix}/FETCH_PROJECTS_SUCCESSFUL`;
export const FETCH_PROJECTS_FAILED = `${prefix}/FETCH_PROJECTS_FAILED`;

export const FETCH_PROJECT_DETAILS_START = `${prefix}/FETCH_PROJECT_DETAILS_START`;
export const FETCH_PROJECT_DETAILS_SUCCESSFUL = `${prefix}/FETCH_PROJECT_DETAILS_SUCCESSFUL`;
export const FETCH_PROJECT_DETAILS_FAILED = `${prefix}/FETCH_PROJECT_DETAILS_FAILED`;

export const FETCH_MCS_START = `${prefix}/FETCH_MCS_START`;
export const FETCH_MCS_SUCCESSFUL = `${prefix}/FETCH_MCS_SUCCESSFUL`;
export const FETCH_MCS_FAILED = `${prefix}/FETCH_MCS_FAILED`;

export const FETCH_KKPT_START = `${prefix}/FETCH_KKPT_START`;
export const FETCH_KKPT_SUCCESSFUL = `${prefix}/FETCH_KKPT_SUCCESSFUL`;
export const FETCH_KKPT_FAILED = `${prefix}/FETCH_KKPT_FAILED`;

export const FETCH_KKPT_DETAILS_START = `${prefix}/FETCH_KKPT_DETAILS_START`;
export const FETCH_KKPT_DETAILS_SUCCESSFUL = `${prefix}/FETCH_KKPT_DETAILS_SUCCESSFUL`;
export const FETCH_KKPT_DETAILS_FAILED = `${prefix}/FETCH_KKPT_DETAILS_FAILED`;

export const FETCH_DOCUMENTS_START = `${prefix}/FETCH_DOCUMENTS_START`;
export const FETCH_DOCUMENTS_SUCCESSFUL = `${prefix}/FETCH_DOCUMENTS_SUCCESSFUL`;
export const FETCH_DOCUMENTS_FAILED = `${prefix}/FETCH_DOCUMENTS_FAILED`;

export const UPDATE_MCS_START = `${prefix}/UPDATE_MCS_START`;
export const UPDATE_MCS_SUCCESSFUL = `${prefix}/UPDATE_MCS_SUCCESSFUL`;
export const UPDATE_MCS_FAILED = `${prefix}/UPDATE_MCS_FAILED`;

export const OPEN_ASSIGN_MODAL = `${prefix}/OPEN_ASSIGN_MODAL`;
export const CLOSE_ASSIGN_MODAL = `${prefix}/CLOSE_ASSIGN_MODAL`;
export const OPEN_DETAILS_MODAL = `${prefix}/OPEN_DETAILS_MODAL`;
export const CLOSE_DETAILS_MODAL = `${prefix}/CLOSE_DETAILS_MODAL`;
