const FETCH_COMMENT_START = "FETCH_COMMENT_START"
const FECTH_COMMENT_SUCCESS = "FECTH_COMMENT_SUCCESS"
const FETCH_COMMENT_FAILED = "FETCH_COMMENT_FAILED"

export {
    FETCH_COMMENT_START,
    FECTH_COMMENT_SUCCESS,
    FETCH_COMMENT_FAILED
}