const prefix = "MAPA_SAMPLE_CSV";

export const FETCH_MAPA_SAMPLE_CSV_START = `${prefix}/FETCH_MAPA_SAMPLE_CSV_START`;
export const FETCH_MAPA_SAMPLE_CSV_SUCCESSFUL = `${prefix}/FETCH_MAPA_SAMPLE_CSV_SUCCESSFUL`;
export const FETCH_MAPA_SAMPLE_CSV_FAILED = `${prefix}/FETCH_MAPA_SAMPLE_CSV_FAILED`;

export const FETCH_POOL_SAMPLE_CSV_START = `${prefix}/FETCH_POOL_SAMPLE_CSV_START`;
export const FETCH_POOL_SAMPLE_CSV_SUCCESSFUL = `${prefix}/FETCH_POOL_SAMPLE_CSV_SUCCESSFUL`;
export const FETCH_POOL_SAMPLE_CSV_FAILED = `${prefix}/FETCH_POOL_SAMPLE_CSV_FAILED`;

export const FETCH_CONTENT_POOL_SAMPLE_CSV_START = `${prefix}/FETCH_CONTENT_POOL_SAMPLE_CSV_START`;
export const FETCH_CONTENT_POOL_SAMPLE_CSV_SUCCESSFUL = `${prefix}/FETCH_CONTENT_POOL_SAMPLE_CSV_SUCCESSFUL`;
export const FETCH_CONTENT_POOL_SAMPLE_CSV_FAILED = `${prefix}/FETCH_CONTENT_POOL_SAMPLE_CSV_FAILED`;

export const SUBMIT_UPLOAD_SAMPLE_CSV_START = `${prefix}/SUBMIT_UPLOAD_SAMPLE_CSV_START`;
export const SUBMIT_UPLOAD_SAMPLE_CSV_SUCCESSFUL = `${prefix}/SUBMIT_UPLOAD_SAMPLE_CSV_SUCCESSFUL`;
export const SUBMIT_UPLOAD_SAMPLE_CSV_FAILED = `${prefix}/SUBMIT_UPLOAD_SAMPLE_CSV_FAILED`;

export const SUBMIT_UPDATE_MAPA_SAMPLE_CSV_START = `${prefix}/SUBMIT_UPDATE_MAPA_SAMPLE_CSV_START`;
export const SUBMIT_UPDATE_MAPA_SAMPLE_CSV_SUCCESSFUL = `${prefix}/SUBMIT_UPDATE_MAPA_SAMPLE_CSV_SUCCESSFUL`;
export const SUBMIT_UPDATE_MAPA_SAMPLE_CSV_FAILED = `${prefix}/SUBMIT_UPDATE_MAPA_SAMPLE_CSV_FAILED`;

export const DELETE_MAPA_SAMPLE_CSV_START = `${prefix}/DELETE_MAPA_SAMPLE_CSV_START`;
export const DELETE_MAPA_SAMPLE_CSV_SUCCESSFUL = `${prefix}/DELETE_MAPA_SAMPLE_CSV_SUCCESSFUL`;
export const DELETE_MAPA_SAMPLE_CSV_FAILED = `${prefix}/DELETE_MAPA_SAMPLE_CSV_FAILED`;

export const DELETE_POOL_SAMPLE_CSV_START = `${prefix}/DELETE_POOL_SAMPLE_CSV_START`;
export const DELETE_POOL_SAMPLE_CSV_SUCCESSFUL = `${prefix}/DELETE_POOL_SAMPLE_CSV_SUCCESSFUL`;
export const DELETE_POOL_SAMPLE_CSV_FAILED = `${prefix}/DELETE_POOL_SAMPLE_CSV_FAILED`;
