const prefix = "MAPA_SAMPLE_MONBER";

export const FETCH_MAPA_SAMPLE_MONBER_START = `${prefix}/FETCH_MAPA_SAMPLE_MONBER_START`;
export const FETCH_MAPA_SAMPLE_MONBER_SUCCESSFUL = `${prefix}/FETCH_MAPA_SAMPLE_MONBER_SUCCESSFUL`;
export const FETCH_MAPA_SAMPLE_MONBER_FAILED = `${prefix}/FETCH_MAPA_SAMPLE_MONBER_FAILED`;

export const FETCH_POOL_SAMPLE_MONBER_START = `${prefix}/FETCH_POOL_SAMPLE_MONBER_START`;
export const FETCH_POOL_SAMPLE_MONBER_SUCCESSFUL = `${prefix}/FETCH_POOL_SAMPLE_MONBER_SUCCESSFUL`;
export const FETCH_POOL_SAMPLE_MONBER_FAILED = `${prefix}/FETCH_POOL_SAMPLE_MONBER_FAILED`;

export const FETCH_CONTENT_MAPA_SAMPLE_MONBER_START = `${prefix}/FETCH_CONTENT_MAPA_SAMPLE_MONBER_START`;
export const FETCH_CONTENT_MAPA_SAMPLE_MONBER_SUCCESSFUL = `${prefix}/FETCH_CONTENT_MAPA_SAMPLE_MONBER_SUCCESSFUL`;
export const FETCH_CONTENT_MAPA_SAMPLE_MONBER_FAILED = `${prefix}/FETCH_CONTENT_MAPA_SAMPLE_MONBER_FAILED`;

export const SUBMIT_UPDATE_MAPA_SAMPLE_MONBER_START = `${prefix}/SUBMIT_UPDATE_MAPA_SAMPLE_MONBER_START`;
export const SUBMIT_UPDATE_MAPA_SAMPLE_MONBER_SUCCESSFUL = `${prefix}/SUBMIT_UPDATE_MAPA_SAMPLE_MONBER_SUCCESSFUL`;
export const SUBMIT_UPDATE_MAPA_SAMPLE_MONBER_FAILED = `${prefix}/SUBMIT_UPDATE_MAPA_SAMPLE_MONBER_FAILED`;

export const DELETE_MAPA_SAMPLE_MONBER_START = `${prefix}/DELETE_MAPA_SAMPLE_MONBER_START`;
export const DELETE_MAPA_SAMPLE_MONBER_SUCCESSFUL = `${prefix}/DELETE_MAPA_SAMPLE_MONBER_SUCCESSFUL`;
export const DELETE_MAPA_SAMPLE_MONBER_FAILED = `${prefix}/DELETE_MAPA_SAMPLE_MONBER_FAILED`;

export const DELETE_POOL_SAMPLE_MONBER_START = `${prefix}/DELETE_POOL_SAMPLE_MONBER_START`;
export const DELETE_POOL_SAMPLE_MONBER_SUCCESSFUL = `${prefix}/DELETE_POOL_SAMPLE_MONBER_SUCCESSFUL`;
export const DELETE_POOL_SAMPLE_MONBER_FAILED = `${prefix}/DELETE_POOL_SAMPLE_MONBER_FAILED`;
