const GET_KKPT_KATEGORI_START = "GET_KKPT_KATEGORI_START"
const GET_KKPT_KATEGORI_SUCCESS = "GET_KKPT_KATEGORI_SUCCESS"
const GET_KKPT_KATEGORI_FAILED = "GET_KKPT_KATEGORI_FAILED"

const CREATE_KKPT_KATEGORI_START = "CREATE_KKPT_KATEGORI_START"
const CREATE_KKPT_KATEGORI_SUCCESS = "CREATE_KKPT_KATEGORI_SUCCESS"
const CREATE_KKPT_KATEGORI_FAILED = "CREATE_KKPT_KATEGORI_FAILED"




export {
    GET_KKPT_KATEGORI_FAILED,
    GET_KKPT_KATEGORI_START,
    GET_KKPT_KATEGORI_SUCCESS,
    CREATE_KKPT_KATEGORI_START,
    CREATE_KKPT_KATEGORI_FAILED,
    CREATE_KKPT_KATEGORI_SUCCESS,
}