const SEND_APPROVAL = "SEND_APPROVAL"
const LOADING_APPROVAL = "LOADING_APPROVAL"
const FAILED_APPROVAL = "FAILED_APPROVAL"
const FAILED_NA = "FAILED_NA"
const LOADING_NA = "LOADING_NA"
const SEND_NA = "SEND_NA"


export {
    SEND_APPROVAL,
    FAILED_APPROVAL,
    SEND_NA,
    FAILED_NA,
    LOADING_NA,
    LOADING_APPROVAL

}